name: dldev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  connectivity_watcher: ^2.0.0
  direct_link: ^0.2.2
  facebook_video_download: ^0.0.4
  flutter:
    sdk: flutter
  flutter_file_downloader: ^2.0.0
  flutter_media_downloader: ^1.0.1
  flutter_reels_downloader: ^0.0.1
  google_fonts: ^4.0.4
  reddit_video_downloader: ^0.1.3
  responsive_builder: ^0.7.0
  youtube_downloader: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
